print('ansh')
print("We are tryig to make changes in file")
print("Please") 
print('My name is haker')
print('me')
print('ansh')
print("We are tryig to make changes in file")
print("Please") 
print('My name is haker')
print('He is a good man')
